Traceback (most recent call last):
  File "/dafnyportfolio/src/solve.py", line 51, in <module>
    portfolio = Portfolio(args.dafny_file, args.procedure_name, args.num_instances, instances, chosen_option_selector,
  File "/dafnyportfolio/src/Portfolio.py", line 18, in __init__
    dynamic_args = self.select_dynamic_args(num_instances)
  File "/dafnyportfolio/src/Portfolio.py", line 30, in select_dynamic_args
    return self.option_selector.create_arguments(num_processes)
  File "/dafnyportfolio/src/diversification/CustomOptionsOptionSelector.py", line 15, in create_arguments
    raise RuntimeError("Stated number of calls and number of provided argument lists do not match")
RuntimeError: Stated number of calls and number of provided argument lists do not match
Traceback (most recent call last):
  File "/dafnyportfolio/src/solve.py", line 51, in <module>
    portfolio = Portfolio(args.dafny_file, args.procedure_name, args.num_instances, instances, chosen_option_selector,
  File "/dafnyportfolio/src/Portfolio.py", line 18, in __init__
    dynamic_args = self.select_dynamic_args(num_instances)
  File "/dafnyportfolio/src/Portfolio.py", line 30, in select_dynamic_args
    return self.option_selector.create_arguments(num_processes)
  File "/dafnyportfolio/src/diversification/CustomOptionsOptionSelector.py", line 15, in create_arguments
    raise RuntimeError("Stated number of calls and number of provided argument lists do not match")
RuntimeError: Stated number of calls and number of provided argument lists do not match
Traceback (most recent call last):
  File "/dafnyportfolio/src/solve.py", line 51, in <module>
    portfolio = Portfolio(args.dafny_file, args.procedure_name, args.num_instances, instances, chosen_option_selector,
  File "/dafnyportfolio/src/Portfolio.py", line 18, in __init__
    dynamic_args = self.select_dynamic_args(num_instances)
  File "/dafnyportfolio/src/Portfolio.py", line 30, in select_dynamic_args
    return self.option_selector.create_arguments(num_processes)
  File "/dafnyportfolio/src/diversification/CustomOptionsOptionSelector.py", line 15, in create_arguments
    raise RuntimeError("Stated number of calls and number of provided argument lists do not match")
RuntimeError: Stated number of calls and number of provided argument lists do not match
Traceback (most recent call last):
  File "/dafnyportfolio/src/solve.py", line 51, in <module>
    portfolio = Portfolio(args.dafny_file, args.procedure_name, args.num_instances, instances, chosen_option_selector,
  File "/dafnyportfolio/src/Portfolio.py", line 18, in __init__
    dynamic_args = self.select_dynamic_args(num_instances)
  File "/dafnyportfolio/src/Portfolio.py", line 30, in select_dynamic_args
    return self.option_selector.create_arguments(num_processes)
  File "/dafnyportfolio/src/diversification/CustomOptionsOptionSelector.py", line 15, in create_arguments
    raise RuntimeError("Stated number of calls and number of provided argument lists do not match")
RuntimeError: Stated number of calls and number of provided argument lists do not match
slurmstepd: error: *** JOB 20714428 ON uc2n543 CANCELLED AT 2022-05-16T17:35:42 DUE TO TIME LIMIT ***

============================= JOB FEEDBACK =============================

NodeName=uc2n543
Job ID: 20714428
Cluster: uc2
User/Group: da1877/iti
State: TIMEOUT (exit code 0)
Nodes: 1
Cores per node: 80
CPU Utilized: 00:00:01
CPU Efficiency: 0.01% of 05:25:20 core-walltime
Job Wall-clock time: 00:04:04
Memory Utilized: 1.82 GB
Memory Efficiency: 2.07% of 87.89 GB
